version: '3.7'

services:
  frontend:
    build: ./frontend
    depends_on:
      - redis
    ports:
      - 3000:3000

  redis:
     image: redis:5.0.5

  backend:
    build: ./backend
    #    volumes:
    #      - ./backend:/backend
    depends_on: 
      - redis

networks:
  front:
  back:
